In [2]:
import pandas as pd
df = pd.read_csv('adult.data.csv')
df.columns = df.columns.str.strip()
df.index = df.index + 1
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
1,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
2,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
3,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
4,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
5,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [3]:
df['race'].value_counts()

race
White                 27816
Black                  3124
Asian-Pac-Islander     1039
Amer-Indian-Eskimo      311
Other                   271
Name: count, dtype: int64

In [7]:
# Create a 'filter' for Males..This filter says "Find every row where the sex is exactly "male"
male = df['sex'] == 'Male'

# Use that filter to create a new, smaller table of just men
men_df = df[male]

# Check the first few rows to make sure no women are in there
men_df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
1,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
2,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
3,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
4,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
8,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K

In [9]:
#Calculate the average of the age of the men
Average_age_of_men =round( men_df['age'].mean(),1)
print('Average age of men:', Average_age_of_men)

Average age of men: 39.4

In [24]:
# Part: Count rows where education is Bachelors
bachelors_count = len(df[df['education'] == 'Bachelors'])

# Whole: Count all rows
total_count = len(df)

# Result
print("Percentage of bachelors:",round((bachelors_count / total_count) * 100,1))

Percentage of bachelors: 16.4

In [28]:
#Create a list of the advanced degrees
Advanced_degrees = ['Bachelors', 'Masters', 'Doctorates']
#Filter those with advanced degrees as "higher education" and thos without it as 'lower education'
higher_education = df[df['education'].isin(Advanced_degrees)]
lower_education = df[~df['education'].isin(Advanced_degrees)]
print(f"High Ed rows: {len(higher_education)}")
print(f"Low Ed rows: {len(lower_education)}")

High Ed rows: 7078
Low Ed rows: 25483

In [29]:
# Count how many in the 'High Ed' group make >50K
high_ed_rich = len(higher_education[higher_education['salary'] == '>50K'])

#Calculate the percentage relative to the High Ed group only
perc_of_rich_high_ed = round((high_ed_rich / len(higher_education)) * 100,1)
print('Percentage of people with advanced education:',perc_of_rich_high_ed)

Percentage of people with advanced education: 44.9

In [31]:
# Use the .min() function to find the lowest value
min_hours = df['hours-per-week'].min()
print(min_hours)

1

In [ ]:
#Filter for only the people who work the minimum hours
num_min_workers = df[df['hours-per-week'] == min_hours]

#Count how many of THEM make >50K
rich_percentage_min_workers = len(num_min_workers[num_min_workers['salary'] == '>50K'])

# Calculate the percentage
rich_percentage = round((rich_percentage_min_workers / len(num_min_workers)) * 100 , 1)
print('rich percentage:',rich_percentage)

rich percentage: 10.0

In [42]:
#Total people per country
total_per_country = df['native-country'].value_counts()

#Rich people (>50K) per country
rich_per_country = df[df['salary'] == '>50K']['native-country'].value_counts()

#The Percentage (This creates a list of percentages for all countries)
country_percentages = (rich_per_country / total_per_country) * 100

#Find the highest name and the highest value
highest_earning_country = country_percentages.idxmax()
highest_earning_country_percentage = round(country_percentages.max(), 1)

print(f"Result: {highest_earning_country} at {highest_earning_country_percentage}%")

Result: Iran at 41.9%

In [43]:
# Filter for people in India AND earning >50K
india_rich = df[(df['native-country'] == 'India') & (df['salary'] == '>50K')]

#Find the most common value in the 'occupation' column
top_IN_occupation = india_rich['occupation'].value_counts().idxmax()

print(f"The top job in India for high earners is: {top_IN_occupation}")

The top job in India for high earners is: Prof-specialty